/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Default Config */
        get: operations["default_config_api_config_default_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Patterns */
        get: operations["patterns_api_patterns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/motifs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Motifs */
        get: operations["motifs_api_motifs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presets */
        get: operations["presets_api_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Preset */
        post: operations["run_preset_api_presets__name__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Step */
        post: operations["step_api_sessions__session_id__step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_api_sessions__session_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/intervene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Intervene */
        post: operations["intervene_api_sessions__session_id__intervene_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/human_phrase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Human Phrase */
        post: operations["human_phrase_api_sessions__session_id__human_phrase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_sessions__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/agents/{agent_id}/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect */
        get: operations["inspect_api_sessions__session_id__agents__agent_id__inspect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_sessions__session_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Session */
        post: operations["import_session_api_sessions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/replay/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay Step */
        post: operations["replay_step_api_sessions__session_id__replay_step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phrases/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Phrase Features */
        post: operations["phrase_features_api_phrases_features_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phrases/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Phrase Render */
        post: operations["phrase_render_api_phrases_render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phrases/transform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Phrase Transform */
        post: operations["phrase_transform_api_phrases_transform_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/motifs/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saved Motifs */
        get: operations["saved_motifs_api_motifs_saved_get"];
        put?: never;
        /** Save Motif */
        post: operations["save_motif_api_motifs_saved_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_experiments_get"];
        put?: never;
        /** Run Experiment */
        post: operations["run_experiment_api_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_experiments__experiment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiment Csv */
        get: operations["experiment_csv_api_experiments__experiment_id__csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Status */
        get: operations["model_status_api_model_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentInspection */
        AgentInspection: {
            agent: components["schemas"]["AgentSnapshot"];
            /** Memory */
            memory: components["schemas"]["MemoryItem"][];
            /**
             * Retrieved
             * @description For the most recent observation
             */
            retrieved?: components["schemas"]["RetrievedMemory"][];
            last_state_inputs?: components["schemas"]["StateUpdateInputs"] | null;
            /** State History */
            state_history: components["schemas"]["StateVector"][];
            /**
             * Information Received
             * @description Log of what this agent actually observed, per step
             */
            information_received?: {
                [key: string]: unknown;
            }[];
        };
        /** AgentParams */
        AgentParams: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Color
             * @default #7c9cff
             */
            color: string;
            /**
             * Instrument
             * @default pluck
             * @enum {string}
             */
            instrument: "sine" | "triangle" | "square" | "pluck" | "bell" | "marimba";
            baseline_override?: components["schemas"]["StateVector"] | null;
            /**
             * Sensitivity
             * @description Multiplier on all state drives
             * @default 1
             */
            sensitivity: number;
            /**
             * Policy Kind
             * @default local
             * @enum {string}
             */
            policy_kind: "local" | "model";
        };
        /** AgentSnapshot */
        AgentSnapshot: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /**
             * Instrument
             * @enum {string}
             */
            instrument: "sine" | "triangle" | "square" | "pluck" | "bell" | "marimba";
            params: components["schemas"]["AgentParams"];
            state: components["schemas"]["StateVector"];
            baseline: components["schemas"]["StateVector"];
            /** Memory Size */
            memory_size: number;
            learner: components["schemas"]["LearnerSnapshot"];
            last_trace?: components["schemas"]["PolicyTrace"] | null;
            /**
             * Frozen State
             * @default false
             */
            frozen_state: boolean;
            /**
             * Coupling Enabled
             * @default true
             */
            coupling_enabled: boolean;
            /**
             * Policy Kind
             * @default local
             * @enum {string}
             */
            policy_kind: "local" | "model";
        };
        /**
         * AudioFeatures
         * @description Features MEASURED from a rendered waveform of the phrase (server-side synth).
         */
        AudioFeatures: {
            /**
             * Kind
             * @default audio
             * @constant
             */
            kind: "audio";
            /** Sample Rate */
            sample_rate: number;
            /** Duration Seconds */
            duration_seconds: number;
            /** Rms */
            rms: number;
            /** Peak */
            peak: number;
            /** Spectral Centroid Hz */
            spectral_centroid_hz: number;
            /**
             * Onset Count Estimate
             * @description Energy-envelope onset estimate; may differ from note_count
             */
            onset_count_estimate: number;
            /**
             * Synth Version
             * @description Identifier of the server synth used; browser playback uses a separate Web Audio implementation of the same instrument spec
             */
            synth_version: string;
        };
        /** ConditionAggregate */
        ConditionAggregate: {
            /** Condition */
            condition: string;
            /**
             * Perturbation
             * @default none
             */
            perturbation: string;
            /** N Runs */
            n_runs: number;
            /** Mean Final Block Score */
            mean_final_block_score: number;
            /** Sd Final Block Score */
            sd_final_block_score: number;
            /** Mean Success Rate */
            mean_success_rate: number;
            /** Sd Success Rate */
            sd_success_rate: number;
            /** Mean Learning Curve */
            mean_learning_curve: number[];
            /** Sd Learning Curve */
            sd_learning_curve: number[];
            /** Per Run Final Block */
            per_run_final_block: number[];
        };
        /**
         * ConditionName
         * @enum {string}
         */
        ConditionName: "full" | "no_history" | "state_fixed" | "state_decoupled" | "symbol" | "perturbed";
        /** ConditionSpec */
        ConditionSpec: {
            /** @default full */
            name: components["schemas"]["ConditionName"];
            /**
             * Perturbation
             * @default none
             * @enum {string}
             */
            perturbation: "none" | "transpose" | "velocity_flatten" | "tempo_shift" | "contour_invert" | "rhythm_shuffle" | "pitch_shuffle";
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * CouplingConfig
         * @description How state influences the policy. All effects are off when enabled=False.
         */
        CouplingConfig: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Uncertainty To Temperature
             * @description tau *= 1 + k*(U - 0.5)
             * @default 1
             */
            uncertainty_to_temperature: number;
            /**
             * Activation To Temperature
             * @description tau *= 1 + k*(0.5 - A)
             * @default 0.6
             */
            activation_to_temperature: number;
            /**
             * Activation To Tempo
             * @description tempo_mult = 1 + k*(A - 0.5)
             * @default 0.3
             */
            activation_to_tempo: number;
            /**
             * Activation To Velocity
             * @description velocity += k*(A - 0.5)
             * @default 30
             */
            activation_to_velocity: number;
            /**
             * Affiliation To Learning Rate
             * @description lr *= 1 + k*affiliation
             * @default 0.5
             */
            affiliation_to_learning_rate: number;
            /**
             * Temperature Min
             * @default 0.05
             */
            temperature_min: number;
            /**
             * Temperature Max
             * @default 5
             */
            temperature_max: number;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            config?: components["schemas"]["ExperimentConfig"] | null;
            condition?: components["schemas"]["ConditionSpec"];
            /** Preset */
            preset?: string | null;
        };
        /** EpisodeSummary */
        EpisodeSummary: {
            /** Step */
            step: number;
            /** Sender Id */
            sender_id: string;
            /** Receiver Id */
            receiver_id: string;
            /** Target Id */
            target_id: number;
            /** Chosen Pattern Id */
            chosen_pattern_id?: number | null;
            /** Score */
            score?: number | null;
            phrase?: components["schemas"]["Phrase"] | null;
            observation?: components["schemas"]["Observation"] | null;
        };
        /** Event */
        Event: {
            /** Seq */
            seq: number;
            /**
             * Step
             * @description Episode index this event belongs to
             */
            step: number;
            /**
             * T
             * @description ISO-8601 wall-clock timestamp (not used for determinism)
             */
            t: string;
            /**
             * Type
             * @enum {string}
             */
            type: "session_created" | "target_assigned" | "phrase_sent" | "phrase_received" | "action_chosen" | "outcome" | "state_update" | "learning_update" | "intervention" | "model_call" | "generated_narrative" | "episode_complete" | "session_reset";
            /** Agent Id */
            agent_id?: string | null;
            /**
             * Visibility
             * @default public
             * @enum {string}
             */
            visibility: "public" | "sender_private" | "experimenter";
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * ExperimentConfig
         * @description Everything a run depends on. Recorded verbatim with each run.
         */
        ExperimentConfig: {
            /**
             * Seed
             * @default 7
             */
            seed: number;
            /**
             * Episodes
             * @default 120
             */
            episodes: number;
            state?: components["schemas"]["StateConfig"];
            coupling?: components["schemas"]["CouplingConfig"];
            learning?: components["schemas"]["LearningConfig"];
            memory?: components["schemas"]["MemoryConfig"];
            music?: components["schemas"]["MusicConfig"];
            task?: components["schemas"]["TaskConfig"];
            model?: components["schemas"]["ModelConfig"];
            /** Agents */
            agents?: components["schemas"]["AgentParams"][];
        };
        /** ExperimentRequest */
        ExperimentRequest: {
            /**
             * Name
             * @default batch
             */
            name: string;
            /** Conditions */
            conditions: components["schemas"]["ConditionSpec"][];
            /** Seeds */
            seeds: number[];
            config?: components["schemas"]["ExperimentConfig"] | null;
        };
        /** ExperimentResult */
        ExperimentResult: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            config: components["schemas"]["ExperimentConfig"];
            /** Runs */
            runs: components["schemas"]["RunMetrics"][];
            /** Aggregates */
            aggregates: components["schemas"]["ConditionAggregate"][];
            /**
             * Notes
             * @description Caveats and honest framing; not conclusions
             */
            notes?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /**
             * Mode Note
             * @default Engineered agent simulation. State labels are operational definitions, not claims about experience.
             */
            mode_note: string;
            model: components["schemas"]["ModelStatus"];
        };
        /**
         * HumanPhraseRequest
         * @description A human acts as sender for one episode.
         */
        HumanPhraseRequest: {
            phrase: components["schemas"]["Phrase"];
            /**
             * Target Id
             * @description If None, a target is drawn by the environment
             */
            target_id?: number | null;
            /** Receiver Id */
            receiver_id?: string | null;
        };
        /**
         * Intervention
         * @description Experimenter interventions. Each one is logged as an `intervention` event
         *     with `payload.effective_from_step` so the UI can show when it took effect.
         *
         *     kinds:
         *       replay_motif       phrase_id (or phrase) -> used as the NEXT sent phrase regardless of sender policy
         *       reset_memory       agent_id -> clears episodic memory AND learned associations; state vector untouched
         *       reset_state        agent_id -> state vector := baseline; memory and associations untouched
         *       freeze_state       agent_id, value -> state updates skipped while frozen
         *       set_coupling       agent_id, value -> state may evolve but cannot influence policy when False
         *       swap_feature       transform (Perturbation) -> applied to every subsequent sent phrase until 'none'
         *       set_param          path (dotted config path), value -> live config change (e.g. state.decay.activation)
         */
        Intervention: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "replay_motif" | "reset_memory" | "reset_state" | "freeze_state" | "set_coupling" | "swap_feature" | "set_param";
            /** Agent Id */
            agent_id?: string | null;
            /** Value */
            value?: boolean | number | string | null;
            /** Phrase Id */
            phrase_id?: string | null;
            phrase?: components["schemas"]["Phrase"] | null;
            /** Transform */
            transform?: ("none" | "transpose" | "velocity_flatten" | "tempo_shift" | "contour_invert" | "rhythm_shuffle" | "pitch_shuffle") | null;
            /** Path */
            path?: string | null;
        };
        /**
         * LearnerSnapshot
         * @description Inspectable learned associations.
         *
         *     receiver_weights: one weight vector per timing pattern over FEATURE_NAMES (+ bias).
         *     sender_values:    Q[target_id][motif_index] expected score.
         */
        LearnerSnapshot: {
            /** Receiver Weights */
            receiver_weights: number[][];
            /** Receiver Bias */
            receiver_bias: number[];
            /** Sender Values */
            sender_values: number[][];
            /** Sender Counts */
            sender_counts: number[][];
            /**
             * Updates
             * @description Number of learning updates applied
             */
            updates: number;
        };
        /** LearningConfig */
        LearningConfig: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Receiver Learning Rate
             * @default 0.15
             */
            receiver_learning_rate: number;
            /**
             * Sender Learning Rate
             * @default 0.2
             */
            sender_learning_rate: number;
            /**
             * Temperature Base
             * @default 0.35
             */
            temperature_base: number;
            /**
             * Receiver L2
             * @default 0.001
             */
            receiver_l2: number;
            /**
             * Optimistic Init
             * @description Initial sender Q value
             * @default 0.5
             */
            optimistic_init: number;
            /**
             * Receiver Init Scale
             * @description Scale of random init for receiver weights
             * @default 0
             */
            receiver_init_scale: number;
        };
        /** MemoryConfig */
        MemoryConfig: {
            /**
             * Capacity
             * @default 200
             */
            capacity: number;
            /**
             * Retrieval K
             * @default 5
             */
            retrieval_k: number;
        };
        /**
         * MemoryItem
         * @description One episodic memory of a musical interaction and its outcome.
         */
        MemoryItem: {
            /** Step */
            step: number;
            /**
             * Role
             * @enum {string}
             */
            role: "sender" | "receiver";
            /** Partner Id */
            partner_id: string;
            /** Phrase Id */
            phrase_id: string;
            /** Motif Id */
            motif_id?: string | null;
            /** Feature Vector */
            feature_vector: number[];
            /**
             * Action
             * @description motif index (sender) or pattern id (receiver)
             */
            action: number;
            /** Score */
            score: number;
            state_before: components["schemas"]["StateVector"];
            state_after: components["schemas"]["StateVector"];
        };
        /** ModelConfig */
        ModelConfig: {
            /**
             * Provider
             * @default none
             * @enum {string}
             */
            provider: "none" | "scripted" | "llamacpp" | "anthropic" | "openai_compatible";
            /**
             * Model Id
             * @default
             */
            model_id: string;
            /** Base Url */
            base_url?: string | null;
            /**
             * Api Key Env
             * @description Name of env var holding the key; the key itself is never stored
             * @default
             */
            api_key_env: string;
            /**
             * Timeout Seconds
             * @default 20
             */
            timeout_seconds: number;
            /**
             * Max Retries
             * @default 1
             */
            max_retries: number;
            /**
             * Call Budget
             * @description Max model calls per session; then fall back to local policy
             * @default 200
             */
            call_budget: number;
            /**
             * Temperature
             * @default 0.2
             */
            temperature: number;
            /** Use For */
            use_for?: ("sender" | "receiver" | "narrative")[];
            /**
             * Narrative Enabled
             * @default false
             */
            narrative_enabled: boolean;
            /**
             * Prompts Dir
             * @default prompts
             */
            prompts_dir: string;
            /**
             * Local Model Path
             * @default models/qwen2.5-0.5b-instruct-q4_k_m.gguf
             */
            local_model_path: string;
            /**
             * N Threads
             * @default 4
             */
            n_threads: number;
        };
        /** ModelStatus */
        ModelStatus: {
            /** Provider */
            provider: string;
            /** Model Id */
            model_id: string;
            /** Available */
            available: boolean;
            /** Tested In This Environment */
            tested_in_this_environment: boolean;
            /** Accepts Audio */
            accepts_audio: boolean;
            /**
             * Input Modality
             * @enum {string}
             */
            input_modality: "symbolic_features" | "symbolic_notes" | "audio" | "none";
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Calls Made
             * @default 0
             */
            calls_made: number;
            /**
             * Call Budget
             * @default 0
             */
            call_budget: number;
        };
        /** MusicConfig */
        MusicConfig: {
            /**
             * Phrase Length Beats
             * @default 8
             */
            phrase_length_beats: number;
            /**
             * Tempo Min
             * @default 80
             */
            tempo_min: number;
            /**
             * Tempo Max
             * @default 160
             */
            tempo_max: number;
            /**
             * Motif Bank
             * @description Named motif bank in resonance/music/motifs.py
             * @default default
             */
            motif_bank: string;
            /**
             * N Motifs
             * @description Sender action space size
             * @default 8
             */
            n_motifs: number;
            /**
             * Feature Weights
             * @description Optional per-feature multipliers applied to phi(phrase); default 1.0
             */
            feature_weights?: {
                [key: string]: number;
            };
            /**
             * Generation Noise
             * @description Velocity/timing jitter sd applied by rng_gen
             * @default 0.05
             */
            generation_noise: number;
        };
        /**
         * Note
         * @description One sounding event. Times are in BEATS relative to phrase start.
         *
         *     Rests are implicit: any span of the phrase without a sounding note is a rest.
         */
        Note: {
            /**
             * Pitch
             * @description MIDI pitch number
             */
            pitch: number;
            /**
             * Onset
             * @description Onset time in beats from phrase start
             */
            onset: number;
            /**
             * Duration
             * @description Duration in beats
             */
            duration: number;
            /**
             * Velocity
             * @description MIDI-style velocity (loudness)
             */
            velocity: number;
        };
        /**
         * Observation
         * @description EXACTLY what the receiver gets. Must never contain the target.
         */
        Observation: {
            /**
             * Channel
             * @enum {string}
             */
            channel: "music" | "symbol";
            /** @description Present for music channel (possibly perturbed) */
            phrase?: components["schemas"]["Phrase"] | null;
            features?: components["schemas"]["SymbolicFeatures"] | null;
            /**
             * Symbol Id
             * @description Present for symbol channel: identity of sender's message
             */
            symbol_id?: number | null;
            /** Sender Id */
            sender_id: string;
            /** Step */
            step: number;
        };
        /**
         * Phrase
         * @description A short structured musical phrase (target length roughly 2-8 seconds).
         */
        Phrase: {
            /** Id */
            id: string;
            /** Notes */
            notes: components["schemas"]["Note"][];
            /** Tempo Bpm */
            tempo_bpm: number;
            /**
             * Length Beats
             * @description Total phrase length in beats, including trailing rest
             */
            length_beats: number;
            /**
             * Instrument
             * @default pluck
             * @enum {string}
             */
            instrument: "sine" | "triangle" | "square" | "pluck" | "bell" | "marimba";
            origin?: components["schemas"]["PhraseOrigin"];
            /**
             * Motif Id
             * @description Base motif this phrase was generated from, if any
             */
            motif_id?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** PhraseFeatures */
        PhraseFeatures: {
            /** Phrase Id */
            phrase_id: string;
            symbolic: components["schemas"]["SymbolicFeatures"];
            audio?: components["schemas"]["AudioFeatures"] | null;
        };
        /** PhraseOrigin */
        PhraseOrigin: {
            /**
             * Kind
             * @default agent
             * @enum {string}
             */
            kind: "agent" | "human" | "preset" | "replay" | "symbol" | "transformed" | "model";
            /** Agent Id */
            agent_id?: string | null;
            /**
             * Source Phrase Id
             * @description For replay/transformed phrases
             */
            source_phrase_id?: string | null;
            /**
             * Transform
             * @description Name of transform applied, if any
             */
            transform?: string | null;
        };
        /**
         * PolicyTrace
         * @description What the policy computed for one decision (scores -> probabilities).
         */
        PolicyTrace: {
            /**
             * Role
             * @enum {string}
             */
            role: "sender" | "receiver";
            /**
             * Policy Kind
             * @enum {string}
             */
            policy_kind: "local" | "model" | "human" | "replay";
            /** Scores */
            scores: number[];
            /** Probabilities */
            probabilities: number[];
            /** Temperature */
            temperature: number;
            /** Temperature Base */
            temperature_base: number;
            /** Coupling Enabled */
            coupling_enabled: boolean;
            /** Chosen */
            chosen: number;
            /** Exploration Draw */
            exploration_draw?: number | null;
            /**
             * Expressive Modulation
             * @description e.g. tempo_multiplier, velocity_offset actually applied
             */
            expressive_modulation?: {
                [key: string]: number;
            };
            /** Notes */
            notes?: string[];
        };
        /** PresetInfo */
        PresetInfo: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Manipulation */
            manipulation: string;
            /** Evidence Criterion */
            evidence_criterion: string;
            /**
             * Constructed Note
             * @description If the result is built by the training schedule, say so
             * @default
             */
            constructed_note: string;
            /** Default Episodes */
            default_episodes: number;
            condition: components["schemas"]["ConditionSpec"];
        };
        /** PresetResult */
        PresetResult: {
            /** Preset */
            preset: string;
            /** Seed */
            seed: number;
            /** Sessions */
            sessions: components["schemas"]["SessionSummary"][];
            /**
             * Comparison
             * @description Preset-specific measured comparison (documented per preset)
             */
            comparison: {
                [key: string]: unknown;
            };
            /**
             * Narrative
             * @description Generated or templated explanation, labelled as such
             */
            narrative?: string | null;
        };
        /** RetrievedMemory */
        RetrievedMemory: {
            item: components["schemas"]["MemoryItem"];
            /** Similarity */
            similarity: number;
        };
        /** RunExport */
        RunExport: {
            /**
             * Format Version
             * @default 1
             */
            format_version: string;
            /** Exported At */
            exported_at: string;
            session: components["schemas"]["SessionSummary"];
            config: components["schemas"]["ExperimentConfig"];
            condition: components["schemas"]["ConditionSpec"];
            /** Events */
            events: components["schemas"]["Event"][];
            final_snapshot: components["schemas"]["SessionSnapshot"];
        };
        /**
         * RunMetrics
         * @description Per-run (one seed, one condition) metrics. Runs are the unit of analysis;
         *     turns within a run are correlated and are NOT treated as independent samples.
         */
        RunMetrics: {
            /** Seed */
            seed: number;
            /** Condition */
            condition: string;
            /**
             * Perturbation
             * @default none
             */
            perturbation: string;
            /** Episodes */
            episodes: number;
            /** Mean Score */
            mean_score: number;
            /**
             * Final Block Score
             * @description Mean score over the last 20% of episodes
             */
            final_block_score: number;
            /**
             * First Block Score
             * @description Mean score over the first 20% of episodes
             */
            first_block_score: number;
            /** Success Rate */
            success_rate: number;
            /**
             * Learning Curve
             * @description Block means (10 blocks)
             */
            learning_curve: number[];
            /**
             * Policy Shift Kl
             * @description KL(final policy || initial policy) per agent, averaged over contexts
             */
            policy_shift_kl: {
                [key: string]: number;
            };
            /**
             * State Effect Persistence
             * @description Steps for activation to return within 0.05 of baseline after a probe pulse, per agent
             */
            state_effect_persistence: {
                [key: string]: number;
            };
            /**
             * Familiar Vs Unfamiliar
             * @description max policy prob for familiar (stored) vs transformed/novel motifs, per agent
             */
            familiar_vs_unfamiliar: {
                [key: string]: number;
            };
            /**
             * Generalization Score
             * @description Score on transposed motifs at test
             */
            generalization_score?: number | null;
            /**
             * State Similarity
             * @description Correlation of agents' activation trajectories
             */
            state_similarity?: number | null;
            /** Extra */
            extra?: {
                [key: string]: number;
            };
        };
        /** RunPresetRequest */
        RunPresetRequest: {
            /** Seed */
            seed?: number | null;
        };
        /** SavedMotif */
        SavedMotif: {
            /** Name */
            name: string;
            phrase: components["schemas"]["Phrase"];
            /** Created At */
            created_at: string;
            features?: components["schemas"]["SymbolicFeatures"] | null;
        };
        /** SessionMetrics */
        SessionMetrics: {
            /** Episodes */
            episodes: number;
            /** Mean Score */
            mean_score: number;
            /**
             * Rolling Score
             * @description Mean over last 20 episodes
             */
            rolling_score: number;
            /**
             * Success Rate
             * @description Fraction with score == 1.0
             */
            success_rate: number;
            /** Score History */
            score_history: number[];
        };
        /** SessionSnapshot */
        SessionSnapshot: {
            /** Id */
            id: string;
            /** Created At */
            created_at: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "replay" | "demo";
            /** Preset */
            preset?: string | null;
            /** Seed */
            seed: number;
            condition: components["schemas"]["ConditionSpec"];
            config: components["schemas"]["ExperimentConfig"];
            /** Step */
            step: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "running" | "finished";
            /** Agents */
            agents: components["schemas"]["AgentSnapshot"][];
            current_episode?: components["schemas"]["EpisodeSummary"] | null;
            metrics: components["schemas"]["SessionMetrics"];
            /** Event Count */
            event_count: number;
            /** Patterns */
            patterns: components["schemas"]["TimingPattern"][];
        };
        /** SessionSummary */
        SessionSummary: {
            /** Id */
            id: string;
            /** Created At */
            created_at: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "replay" | "demo";
            /** Preset */
            preset: string | null;
            /** Seed */
            seed: number;
            condition: components["schemas"]["ConditionSpec"];
            /** Step */
            step: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "running" | "finished";
        };
        /** StateConfig */
        StateConfig: {
            /**
             * @default {
             *       "activation": 0.5,
             *       "expected_value": 0.5,
             *       "uncertainty": 0.5,
             *       "affiliation": 0
             *     }
             */
            baseline: components["schemas"]["StateVector"];
            /**
             * Inertia
             * @description Fraction of the previous value retained per step; drive is scaled by (1 - inertia)
             */
            inertia?: {
                [key: string]: number;
            };
            /**
             * Decay
             * @description Per-step pull toward baseline
             */
            decay?: {
                [key: string]: number;
            };
            /**
             * Max Step
             * @description Bound on |delta| per step
             */
            max_step?: {
                [key: string]: number;
            };
            /**
             * Acoustic Activation Enabled
             * @description HAND-AUTHORED: dense/loud phrases push activation up. Switchable; not a learned association.
             * @default true
             */
            acoustic_activation_enabled: boolean;
            /**
             * Acoustic Activation Gain
             * @default 0.5
             */
            acoustic_activation_gain: number;
            /** Prediction Error Gain */
            prediction_error_gain?: {
                [key: string]: number;
            };
            /** Outcome Gain */
            outcome_gain?: {
                [key: string]: number;
            };
            /**
             * Partner Similarity Gain
             * @description HAND-AUTHORED: similar partner phrase nudges affiliation up
             * @default 0.2
             */
            partner_similarity_gain: number;
        };
        /**
         * StateUpdateInputs
         * @description Everything that fed one state update, so the inspector can show cause -> effect.
         */
        StateUpdateInputs: {
            /**
             * Music Drive
             * @description Hand-authored acoustic contribution per state dim (0 if disabled)
             */
            music_drive?: {
                [key: string]: number;
            };
            /** Prediction Error */
            prediction_error?: number | null;
            /** Outcome */
            outcome?: number | null;
            /**
             * Partner Similarity
             * @description Cosine similarity of partner's phrase features to own last phrase (0..1)
             */
            partner_similarity?: number | null;
            /**
             * Decay Applied
             * @default true
             */
            decay_applied: boolean;
            /**
             * Frozen
             * @default false
             */
            frozen: boolean;
            /** Notes */
            notes?: string[];
        };
        /**
         * StateVector
         * @description Bounded engineered state. Operational definitions:
         *
         *     activation      [0,1]  drive/arousal-like scalar. Raised by dense/loud input (if the
         *                            hand-authored acoustic influence is enabled) and by surprising
         *                            outcomes; decays toward baseline. Modulates expressive tempo/velocity
         *                            and exploration temperature when coupling is enabled.
         *     expected_value  [0,1]  running expectation of the coordination score.
         *     uncertainty     [0,1]  running magnitude of recent prediction error.
         *     affiliation    [-1,1]  running credit toward the partner: rises with shared success,
         *                            falls with shared failure. Scales effective learning rate when coupled.
         */
        StateVector: {
            /** Activation */
            activation: number;
            /** Expected Value */
            expected_value: number;
            /** Uncertainty */
            uncertainty: number;
            /** Affiliation */
            affiliation: number;
        };
        /** StepRequest */
        StepRequest: {
            /**
             * N
             * @default 1
             */
            n: number;
        };
        /** StepResult */
        StepResult: {
            /** Events */
            events: components["schemas"]["Event"][];
            snapshot: components["schemas"]["SessionSnapshot"];
        };
        /**
         * SymbolicFeatures
         * @description Features computed deterministically from the NOTE LIST (not from audio).
         */
        SymbolicFeatures: {
            /**
             * Kind
             * @default symbolic
             * @constant
             */
            kind: "symbolic";
            /** Note Count */
            note_count: number;
            /** Duration Seconds */
            duration_seconds: number;
            /**
             * Note Density
             * @description Notes per second
             */
            note_density: number;
            /**
             * Rhythmic Regularity
             * @description 1 - normalised std of inter-onset intervals, in [0,1]
             */
            rhythmic_regularity: number;
            /**
             * Syncopation
             * @description Fraction of onsets not on an eighth-note grid, in [0,1]
             */
            syncopation: number;
            /** Mean Pitch */
            mean_pitch: number;
            /**
             * Pitch Range
             * @description max pitch - min pitch in semitones
             */
            pitch_range: number;
            /**
             * Contour
             * @description Normalised slope of pitch over time, in [-1,1]
             */
            contour: number;
            /**
             * Contour Class
             * @enum {string}
             */
            contour_class: "rising" | "falling" | "arch" | "valley" | "flat" | "zigzag";
            /**
             * Repetition
             * @description Fraction of repeated (interval, ioi) bigrams, in [0,1]
             */
            repetition: number;
            /**
             * Interval Histogram
             * @description Fractions of melodic intervals by class: [unison, step(1-2), third(3-4), fourth/fifth(5-7), large(>7)]
             */
            interval_histogram: number[];
            /** Mean Velocity */
            mean_velocity: number;
            /**
             * Velocity Variation
             * @description std(velocity)/mean(velocity)
             */
            velocity_variation: number;
            /**
             * Dissonance Proxy
             * @description Fraction of melodic intervals whose pitch-class interval is in {1, 6, 11} semitones (minor 2nd, tritone, major 7th). Defined here; not a perceptual claim.
             */
            dissonance_proxy: number;
            /** Tempo Bpm */
            tempo_bpm: number;
            /**
             * Vector
             * @description Normalised feature vector phi(phrase) used by learners (fixed order, see FEATURE_NAMES)
             */
            vector: number[];
        };
        /** TaskConfig */
        TaskConfig: {
            /**
             * Kind
             * @default timing
             * @constant
             */
            kind: "timing";
            /**
             * N Patterns
             * @default 4
             */
            n_patterns: number;
            /**
             * Partial Credit
             * @default true
             */
            partial_credit: boolean;
        };
        /**
         * TimingPattern
         * @description A target rhythm for the cooperative timing task. Public knowledge (the set),
         *     but WHICH one is the target in an episode is private to the sender.
         */
        TimingPattern: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Onsets
             * @description Onset times in beats within a 4-beat bar
             */
            onsets: number[];
            /**
             * Length Beats
             * @default 4
             */
            length_beats: number;
        };
        /** TransformRequest */
        TransformRequest: {
            phrase: components["schemas"]["Phrase"];
            /**
             * Transform
             * @enum {string}
             */
            transform: "none" | "transpose" | "velocity_flatten" | "tempo_shift" | "contour_invert" | "rhythm_shuffle" | "pitch_shuffle";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    default_config_api_config_default_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentConfig"];
                };
            };
        };
    };
    patterns_api_patterns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimingPattern"][];
                };
            };
        };
    };
    motifs_api_motifs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Phrase"][];
                };
            };
        };
    };
    presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetInfo"][];
                };
            };
        };
    };
    run_preset_api_presets__name__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunPresetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    step_api_sessions__session_id__step_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_sessions__session_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intervene_api_sessions__session_id__intervene_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Intervention"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    human_phrase_api_sessions__session_id__human_phrase_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HumanPhraseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_sessions__session_id__events_get: {
        parameters: {
            query?: {
                from_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_api_sessions__session_id__agents__agent_id__inspect_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentInspection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_sessions__session_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunExport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_session_api_sessions_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunExport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_step_api_sessions__session_id__replay_step_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    phrase_features_api_phrases_features_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Phrase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhraseFeatures"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    phrase_render_api_phrases_render_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Phrase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    phrase_transform_api_phrases_transform_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransformRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Phrase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saved_motifs_api_motifs_saved_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedMotif"][];
                };
            };
        };
    };
    save_motif_api_motifs_saved_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedMotif"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedMotif"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_experiments_api_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResult"][];
                };
            };
        };
    };
    run_experiment_api_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_api_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_csv_api_experiments__experiment_id__csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_status_api_model_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatus"];
                };
            };
        };
    };
}
