/**
 * Convenience aliases over the GENERATED OpenAPI types (./schema.d.ts).
 * Never hand-edit schema.d.ts; regenerate with `make types`.
 */
import type { components } from './schema'

type S = components['schemas']

export type Note = S['Note']
export type Phrase = S['Phrase']
export type PhraseOrigin = S['PhraseOrigin']
export type Instrument = Phrase['instrument']
export type TimingPattern = S['TimingPattern']
export type SymbolicFeatures = S['SymbolicFeatures']
export type AudioFeatures = S['AudioFeatures']
export type PhraseFeatures = S['PhraseFeatures']
export type StateVector = S['StateVector']
export type StateUpdateInputs = S['StateUpdateInputs']
export type MemoryItem = S['MemoryItem']
export type RetrievedMemory = S['RetrievedMemory']
export type LearnerSnapshot = S['LearnerSnapshot']
export type PolicyTrace = S['PolicyTrace']
export type ExperimentConfig = S['ExperimentConfig']
export type StateConfig = S['StateConfig']
export type CouplingConfig = S['CouplingConfig']
export type LearningConfig = S['LearningConfig']
export type MemoryConfig = S['MemoryConfig']
export type MusicConfig = S['MusicConfig']
export type TaskConfig = S['TaskConfig']
export type ModelConfig = S['ModelConfig']
export type AgentParams = S['AgentParams']
export type ConditionName = S['ConditionName']
export type ConditionSpec = S['ConditionSpec']
export type Perturbation = ConditionSpec['perturbation']
export type Event = S['Event']
export type EventType = Event['type']
export type Observation = S['Observation']
export type AgentSnapshot = S['AgentSnapshot']
export type EpisodeSummary = S['EpisodeSummary']
export type SessionMetrics = S['SessionMetrics']
export type SessionSnapshot = S['SessionSnapshot']
export type SessionSummary = S['SessionSummary']
export type CreateSessionRequest = S['CreateSessionRequest']
export type StepRequest = S['StepRequest']
export type StepResult = S['StepResult']
export type Intervention = S['Intervention']
export type InterventionKind = Intervention['kind']
export type HumanPhraseRequest = S['HumanPhraseRequest']
export type AgentInspection = S['AgentInspection']
export type RunExport = S['RunExport']
export type RunMetrics = S['RunMetrics']
export type ConditionAggregate = S['ConditionAggregate']
export type ExperimentRequest = S['ExperimentRequest']
export type ExperimentResult = S['ExperimentResult']
export type PresetInfo = S['PresetInfo']
export type PresetResult = S['PresetResult']
export type ModelStatus = S['ModelStatus']
export type HealthResponse = S['HealthResponse']
export type SavedMotif = S['SavedMotif']
export type RunPresetRequest = S['RunPresetRequest']
export type TransformRequest = S['TransformRequest']

export type StateDim = keyof StateVector
